# Cloudflare Tunnel Configuration
# Replace [TUNNEL_ID] with your actual tunnel ID after creating the tunnel

tunnel: 15d1aab1-b4c8-445e-98d3-eb20b78f5e9a
credentials-file: /Users/sudarshanprakash/.cloudflared/15d1aab1-b4c8-445e-98d3-eb20b78f5e9a.json

ingress:
  # Route all traffic to local API server
  - hostname: optiondata.stingfu.com
    service: http://localhost:8002
    originRequest:
      noTLSVerify: true
      connectTimeout: 30s
      tlsTimeout: 10s
      httpHostHeader: localhost:8001
  
  # Catch-all rule (required)
  - service: http_status:404

# Optional: Logging configuration
# log: 
#   level: info
#   file: /Users/anujsainicse/.cloudflared/tunnel.log